export const TEST_CODE_STRING = 'Hello World!';
export const TEST_MODE = 'javascript';
export const TEST_PRESET = 'default';
export const TEST_THEME = 'default';
export const TEST_USE_LINE_NUMBERS = false;
export const TEST_WIDTH = 1280;
export const TEST_HEIGHT = 720;
export const TEST_SCROLL_PERCENTAGE = 100;
export const TEST_MAX_SCREENSHOTS = 2;
